package GUI;

import DAO.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import entidades.Clientes;
import controladores.ClientesJpaController;
import javax.swing.JOptionPane;

/**
 *
 * @author he-ds
 */
public class Vista_ClientesDlg extends javax.swing.JDialog
{
    Cliente cliente;
    Integer id;
    String nombre;
    String direccion;
    String rfc;
    String telefono;
    DefaultTableModel modelo;
    ClientesJpaController controlador = new ClientesJpaController();

    /**
     * Creates new form Vista_ClientesDlg
     */
    public Vista_ClientesDlg(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("RFC");
        modelo.addColumn("Telefono");
        this.clienteTbl.setModel(modelo);
        
        consultarTodos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        idLbl = new javax.swing.JLabel();
        rfcLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        telefonoLbl = new javax.swing.JLabel();
        direccionLbl = new javax.swing.JLabel();
        idTxtbox = new javax.swing.JTextField();
        eliminarBtn = new javax.swing.JButton();
        nombreTxtbox = new javax.swing.JTextField();
        direccionTxtbox = new javax.swing.JTextField();
        rfcTxtbox = new javax.swing.JTextField();
        telefonoTxtbox = new javax.swing.JTextField();
        guardarbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });

        idLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLbl.setText("Id");

        rfcLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rfcLbl.setText("Rfc");

        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombreLbl.setText("Nombre");

        telefonoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefonoLbl.setText("Telefono");

        direccionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        direccionLbl.setText("Dirección");

        idTxtbox.setToolTipText("Click afuera para limpiar");
        idTxtbox.setPreferredSize(new java.awt.Dimension(170, 22));

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminarBtnActionPerformed(evt);
            }
        });

        nombreTxtbox.setPreferredSize(new java.awt.Dimension(170, 22));

        direccionTxtbox.setPreferredSize(new java.awt.Dimension(170, 22));

        rfcTxtbox.setPreferredSize(new java.awt.Dimension(170, 22));

        telefonoTxtbox.setPreferredSize(new java.awt.Dimension(170, 22));

        guardarbtn.setText("Guardar");
        guardarbtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guardarbtnActionPerformed(evt);
            }
        });

        clienteTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        clienteTbl.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                clienteTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clienteTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreLbl)
                    .addComponent(rfcLbl)
                    .addComponent(telefonoLbl)
                    .addComponent(idLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nombreTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfcTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarbtn)
                        .addGap(26, 26, 26)
                        .addComponent(eliminarBtn)))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(nombreTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rfcLbl)
                            .addComponent(rfcTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonoLbl)
                            .addComponent(telefonoTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarbtn)
                            .addComponent(eliminarBtn))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void guardarbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guardarbtnActionPerformed
    {//GEN-HEADEREND:event_guardarbtnActionPerformed
        // TODO add your handling code here:
        
        if (idTxtbox.getText().length() != 0 && nombreTxtbox.getText().length() != 0
                && direccionTxtbox.getText().length() != 0 && rfcTxtbox.getText().length() != 0
                && telefonoTxtbox.getText().length() != 0)
        {
            id = Integer.parseInt(idTxtbox.getText().toUpperCase());
            nombre = nombreTxtbox.getText().toUpperCase();
            direccion = direccionTxtbox.getText().toUpperCase();
            rfc = rfcTxtbox.getText().toUpperCase();
            telefono = telefonoTxtbox.getText().toUpperCase();

            cliente = new Cliente(id, nombre, direccion, rfc, telefono);

            String msj = cliente.inserta();
            if(msj.contains("already exists"))
            {
                System.out.println(" ID ya existe");
            }
            
            limpiarTextbox();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos", "Cliente", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Ingrese todos los datos!");
        }
        
        consultarTodos();
    }//GEN-LAST:event_guardarbtnActionPerformed

    private boolean comparaCliente()
    {    
        List<Clientes> results = controlador.findClientesEntities();
        
        for (int i = 0; i < results.size(); i++)
        {
            if(results.get(i).getNombre()==nombreTxtbox.getText() &&
                    results.get(i).getDireccion()==direccionTxtbox.getText() &&
                    results.get(i).getRfc()==rfcTxtbox.getText() &&
                    results.get(i).getTelefono()==telefonoTxtbox.getText())
            {
                return true;
            }            
        }
        return false;            
    }
    
    private void clienteTblMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_clienteTblMouseClicked
    {//GEN-HEADEREND:event_clienteTblMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) clienteTbl.getModel();
        String idSocio=model.getValueAt(clienteTbl.getSelectedRow(), 0).toString();
        String nombre=model.getValueAt(clienteTbl.getSelectedRow(), 1).toString();
        String direccion=model.getValueAt(clienteTbl.getSelectedRow(), 2).toString();
        String rfc=model.getValueAt(clienteTbl.getSelectedRow(), 3).toString();
        String telefono=model.getValueAt(clienteTbl.getSelectedRow(), 4).toString();
        
        idTxtbox.setText(idSocio);
        nombreTxtbox.setText(nombre);
        direccionTxtbox.setText(direccion);
        rfcTxtbox.setText(rfc);
        telefonoTxtbox.setText(telefono);
    }//GEN-LAST:event_clienteTblMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        // TODO add your handling code here:
        limpiarTextbox();
    }//GEN-LAST:event_formMouseClicked

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminarBtnActionPerformed
    {//GEN-HEADEREND:event_eliminarBtnActionPerformed
        // TODO add your handling code here:
//        if (idTxtbox.getText().length() != 0 && nombreTxtbox.getText().length() != 0
//                && direccionTxtbox.getText().length() != 0 && rfcTxtbox.getText().length() != 0
//                && telefonoTxtbox.getText().length() != 0)
        if(idTxtbox.getText().length() != 0)
        {
            id = Integer.parseInt(idTxtbox.getText());
            
            try
            {
                controlador.destroy(id);
            } catch (Exception e)
            {
                System.out.println("Error: "+e.getMessage());
            }
            
            limpiarTextbox();
        }else
        {
            JOptionPane.showMessageDialog(null, "Seleccione en la tabla o escriba un ID", "Cliente", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Seleccione en la tabla o escriba un ID!");
        }
        consultarTodos();       
    }//GEN-LAST:event_eliminarBtnActionPerformed
    public void consultarTodos()
    {        
//        if(clienteTemp.obtieneLista()!=null)
//        {
        List<Clientes> results = controlador.findClientesEntities();//clienteTemp.obtieneLista();
        
        DefaultTableModel model = (DefaultTableModel) clienteTbl.getModel();
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }
        Object rowData[] = new Object[5];
        for (int i = 0; i < results.size(); i++)
        {
            rowData[0] = results.get(i).getId();
            rowData[1] = results.get(i).getNombre();
            rowData[2] = results.get(i).getDireccion();
            rowData[3] = results.get(i).getRfc();
            rowData[4] = results.get(i).getTelefono();
            model.addRow(rowData);
        }
//        }

    }
    public void limpiarTextbox(){
        idTxtbox.setText("");
        nombreTxtbox.setText("");
        direccionTxtbox.setText("");
        rfcTxtbox.setText("");
        telefonoTxtbox.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Vista_ClientesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Vista_ClientesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Vista_ClientesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Vista_ClientesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Vista_ClientesDlg dialog = new Vista_ClientesDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clienteTbl;
    private javax.swing.JLabel direccionLbl;
    private javax.swing.JTextField direccionTxtbox;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton guardarbtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxtbox;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxtbox;
    private javax.swing.JLabel rfcLbl;
    private javax.swing.JTextField rfcTxtbox;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JTextField telefonoTxtbox;
    // End of variables declaration//GEN-END:variables
}
